[workspace]
authors = ["w32zhong <clock126@126.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "simpsons-intelligence"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025072205,<26"
notebook = ">=7.4.4,<8"
numpy = ">=2.3.1,<3"
matplotlib = ">=3.10.3,<4"
jupyter-collaboration = ">=4.1.0,<5"
