[workspace]
authors = ["w32zhong <clock126@126.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "simpsons-intelligence"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
cuda = "12.0"

[dependencies]
modular = ">=25.5.0.dev2025072205,<26"
notebook = ">=7.4.4,<8"
jupyter-collaboration = ">=4.1.0,<5"
graphviz = ">=13.1.1,<14"
pytorch-gpu = "*"

[pypi-dependencies]
graphviz = ">=0.21, <0.22"
numpy = "*"
matplotlib = "*"
